# curl -X POST   http://localhost:8080/auth/signin    -H 'Content-Type: application/json'    -d '{
#"username": "user",
#"password": "password"
#}'
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
"username": "user",
"password": "password"
}

###

# curl -X POST
#  http://localhost:8080/
#  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTU3ODE0NDY0NywiZXhwIjoxNTc4MTQ4MjQ3fQ.Ok7U17K1NteGMyF1Fu7hdMAH3RVz2DOGLXe20832P9k'
#  -H 'Content-Type: application/json' \
POST http://localhost:8080/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTU3ODE0NDY0NywiZXhwIjoxNTc4MTQ4MjQ3fQ.Ok7U17K1NteGMyF1Fu7hdMAH3RVz2DOGLXe20832P9k
Content-Type: application/json

###

